language: node_js
node_js:
  - "16.9"
script:
  - npm run test
  - npm run build:all
deploy:
  - provider: npm
    tags: true
    email: "$NPM_EMAIL"
    api_key: $NPM_TOKEN
    skip_cleanup: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true

after_success:
  - npm run report-coverage
  - npm run docs
